---
# #######################
# Following Tasks will be executed.
# # 1. 'hosts' file will be created from the template files.
# # 2. Host entry for all the S3 Server nodes will be added to the 'hosts' file
# # 3. Host entry for all the S3 client nodes will be added to the 'hosts' file
# #######################
# # Variables 'nodes' and 'clients' need be passed as arguments as per the following example.
# # --extra-vars '{"nodes":{"1": "node1", "2": "node2","3": "node3" , "clients":{"1": "client1", "2": "client2"}} '
# #######################

 - name : create hosts file from hosts_template.bak
   copy:
    src: files/hosts_template
    dest: "{{ playbook_dir }}/hosts"

 - name: create server hosts entry
   lineinfile:
    path: "{{ playbook_dir }}/hosts"
    insertafter: '\[nodes\]'
    line:
     "srvnode-{{ item.key }} ansible_host={{ item.value }} "
   with_dict: "{{ nodes }}"

 - name: create clients hosts entry
   lineinfile:
    path: "{{ playbook_dir }}/hosts"
    insertafter: '\[clients\]'
    line:
     "clientnode-{{ item.key }} ansible_host={{ item.value }} "
   with_dict: "{{ clients }}"
